language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - composer self-update
  - npm cache clean -f

before_script:
  - npm install -g n
  - n stable
  - npm install -g dredd@3.4.1
  - composer install --no-interaction

after_success:
  - dredd

script:
  - vendor/bin/phpunit