language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_install:
  - composer install --no-interaction
  - npm install -g dredd@3.4.1

after_success:
    - dredd

script:
  - vendor/bin/phpunit