language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - composer self-update

before_script:
  - npm install -g dredd@3.4.1
  - composer install --no-interaction
  - php artisan serve

after_success:
  - dredd

script:
  - vendor/bin/phpunit