language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction

before_install:
  - npm install -g dredd@3.4.1
  - php artisan serve

after_success:
    - dredd

script:
  - vendor/bin/phpunit